Update Roadmap
keylime/keylime pull request #1036
Opened 2022-06-20 10:08 UTC by THS-on

This updates the general Roadmap. 

@maugustosilva can you provide a small text about "durable attestation"?

2022-06-20 14:18 UTC, mpeters approved these changes

2022-06-20 15:56 UTC, maugustosilva commented
## Durable Attestation
#### Q4-2022

Attestation "artifacts" (e.g., quotes, IMA logs) collected by the `verifier` can be optionally written on a "persistent time-series like store", allowing a thrid-party (e.g., an auditor) to assess the state of a given node N at a certain date D, far in the past. This functionality will include the use of a "transparency log" to record the association between an given EK and AIK, and a new command-line tool (`keylime_attest`) to perform "offline attestation")

2022-06-20 20:19 UTC, mpeters requested changes

2022-06-20 20:19 UTC, mpeters commented on ROADMAP.md
> +time-series like store", allowing a thrid-party (e.g., an auditor) to assess the state of a given node N at a certain date D,
"thrid" should be "third"

2022-06-21 06:15 UTC, THS-on commented on ROADMAP.md
> +time-series like store", allowing a thrid-party (e.g., an auditor) to assess the state of a given node N at a certain date D,
fixed

2022-06-21 14:23 UTC, merged