Fix broken URLs in README (Additional Reading)
keylime/keylime pull request #1042
Opened 2022-07-04 15:43 UTC by mayaCostantini

Fix URLs not found in project main README Additional Reading section.

2022-07-04 16:32 UTC, aplanas requested changes
Thanks for the fix!

IMHO it should point to the `raw` version for the documents instead of the `blob` one

2022-07-05 13:54 UTC, sergio-correia approved these changes
Thanks for fixing these!

2022-07-05 14:13 UTC, mpeters commented
> Basically LGTM.
> 
> If anyone has a comment about keeping the `pptx` as raw (as it is already done in this PR), but pointing the `md`, or `pdf` to the blobs because github is able to render it, I would be OK too.

Yeah, that could be helpful to keep them formatted for new users. @mayaCostantini would you be willing to make that change to this PR?

2022-07-06 08:08 UTC, aplanas approved these changes

2022-07-06 15:07 UTC, merged