The verifier can selectively load only a subset of columns from the `allowlist` table.
keylime/keylime pull request #1200
Opened 2022-11-21 18:32 UTC by maugustosilva

With this PR, the `verifier` can load only a few colmuns from the `allowlist` table, giving it the ability to selectively decide if the full row needs to be loaded (very useful for implementing a proxy or cache).

In addition to that, a new column, `generator` is introduced to reflect the fact that an IMA policy was supplied by an user, versus automatically generated as "empty" from within the verifier.

Signed-off-by: Marcio Silva <marcio.a.silva@ibm.com>

2022-11-21 20:00 UTC, mpeters requested changes

2022-11-21 21:49 UTC, stefanberger commented
From you r commit:

```
With this PR, the `verifier` can load only a few colmuns from the
`allowlist` table, giving it the ability to selectively decide if the
full row needs to be loaded (very useful for implementing a proxy or
cache).
```

Regarding **full row**: One could also introduce a column `modified` that covers a full row's update and not just indicates that those components covered by the checksum changed.

I had this here in my PR while it was still polling:

```
commit fbf936b64d35a39b9386bf2c03a64ad178e6e643
Author: Stefan Berger <stefanb@linux.ibm.com>
Date:   Thu Nov 17 19:31:52 2022 -0500

    verifier: Add timestamp 'modified' column to VerifierAllowlist

    Add a timestamp 'modified' column to the VerifierAllowlist that
    must not be NULL and when adding the column it is initialized with
    a default date. The column is automatially set to the current
    time on insert and also to the current time on updates.

    Signed-off-by: Stefan Berger <stefanb@linux.ibm.com>

diff --git a/keylime/db/verifier_db.py b/keylime/db/verifier_db.py
index d677814..b5b5ea8 100644
--- a/keylime/db/verifier_db.py
+++ b/keylime/db/verifier_db.py
@@ -1,4 +1,6 @@
-from sqlalchemy import Column, ForeignKey, Integer, LargeBinary, PickleType, String, Text, schema
+import datetime
+
+from sqlalchemy import TIMESTAMP, Column, ForeignKey, Integer, LargeBinary, PickleType, String, Text, schema
 from sqlalchemy.ext.declarative import declarative_base
 from sqlalchemy.orm import relationship

@@ -60,3 +62,4 @@ class VerifierAllowlist(Base):
     checksum = Column(String(128))
     tpm_policy = Column(Text())
     ima_policy = Column(Text().with_variant(Text(429400000), "mysql"))
+    modified = Column(TIMESTAMP, nullable=False, default=datetime.datetime.now, onupdate=datetime.datetime.now)
diff --git a/keylime/migrations/versions/90e4f63b79aa_add_modified_to_allowlist.py b/keylime/migrations/versions/90e4f63b79aa_add_modified_to_allowlist.py
new file mode 100644
index 0000000..50bc650
--- /dev/null
+++ b/keylime/migrations/versions/90e4f63b79aa_add_modified_to_allowlist.py
@@ -0,0 +1,44 @@
+"""add_modified_to_allowlist
+
+Revision ID: 90e4f63b79aa
+Revises: 2fbc0fb8fa4d
+Create Date: 2022-11-17 22:22:55.602069
+
+"""
+import sqlalchemy as sa
+from alembic import op
+
+# revision identifiers, used by Alembic.
+revision = "90e4f63b79aa"
+down_revision = "2fbc0fb8fa4d"
+branch_labels = None
+depends_on = None
+
+
+def upgrade(engine_name):
+    globals()[f"upgrade_{engine_name}"]()
+
+
+def downgrade(engine_name):
+    globals()[f"downgrade_{engine_name}"]()
+
+
+def upgrade_registrar():
+    pass
+
+
+def downgrade_registrar():
+    pass
+
+
+def upgrade_cloud_verifier():
+    # sqlite only lets us put a "0" into modified column when adding column
+    # Replace it with a true timestamp in 2nd step
+    op.add_column(
+        "allowlists",
+        sa.Column("modified", sa.TIMESTAMP, nullable=False, server_default="2000-01-01 00:00:00"),
+    )
+
+
+def downgrade_cloud_verifier():
+    op.drop_column("allowlists", "modified")
```

2022-11-22 08:08 UTC, aplanas commented on keylime/ima/ima.py
> +        "generator": 1,
Agreed. I am not sure if this is a "version" or a boolean type

2022-11-22 08:11 UTC, aplanas commented on keylime/ima/ima.py
> +
```python
class Generator:
      Unknown = 0
      EmptyAllowList = 1
      CompatibleAllowList = 2
      LegacyAllowList = 3
```

2022-11-22 08:12 UTC, aplanas commented on keylime/ima/ima.py
> +        alist["meta"]["generator"] = 2
`alist["meta"]["generator"] = Generator.CompatibleAllowList`

2022-11-22 08:12 UTC, aplanas commented on keylime/ima/ima.py
> +        alist["meta"]["generator"] = 3
`alist["meta"]["generator"] = Generator.LegacyAllowList`

2022-11-22 08:12 UTC, aplanas commented on keylime/ima/ima.py
> +                ima_policy_db_format["generator"] = 0
`ima_policy_db_format["generator"] = Generator.Unknown`

2022-11-22 16:15 UTC, maugustosilva commented on keylime/ima/ima.py
> +        "generator": 1,
fixed

2022-11-22 16:15 UTC, maugustosilva commented on keylime/ima/ima.py
> +
done

2022-11-22 16:15 UTC, maugustosilva commented on keylime/ima/ima.py
> +        alist["meta"]["generator"] = 2
done

2022-11-22 16:15 UTC, maugustosilva commented on keylime/ima/ima.py
> +        alist["meta"]["generator"] = 3
done

2022-11-22 16:15 UTC, maugustosilva commented on keylime/ima/ima.py
> +                ima_policy_db_format["generator"] = 0
done

2022-11-22 19:50 UTC, mpeters approved these changes

2022-11-22 19:50 UTC, merged