Add missing test from keylime testsuite to e2e plan
keylime/keylime pull request #1335
Opened 2023-03-17 14:40 UTC by Koncpa

Also set boolean faked_measured_boot_log to yes.

2023-03-18 13:46 UTC, maugustosilva commented
/packit retest-failed

2023-03-20 14:26 UTC, kkaarreell commented on packit-ci.fmf
> +     - /functional/measured-boot-policy-sanity
@Koncpa This one should not be added

2023-03-20 14:52 UTC, kkaarreell commented
> The new test (`durable-attestion-sanity-on-localhost`) is failing...

Since we have switched to the rust agent, in order to make these measured boot related tests to work we need to point them to the fake measured boot log through
```
environment:
  TPM_BINARY_MEASUREMENTS: /var/tmp/binary_bios_measurements
```
in each plan. 
Unfortunately, @Koncpa is away this week so this will have to wait a bit.

2023-03-20 14:53 UTC, kkaarreell requested changes

2023-03-20 20:42 UTC, maugustosilva commented
/packit retest-failed

2023-03-22 14:06 UTC, maugustosilva commented
@kkaarreell I can confirm that all tests pass with the changes you suggested (just FYI, @Koncpa)

2023-03-29 10:46 UTC, Koncpa commented on packit-ci.fmf
> +    faked_measured_boot_log: yes
Shouled be resolved.

2023-03-29 10:46 UTC, Koncpa commented on packit-ci.fmf
> +     - /functional/measured-boot-policy-sanity
DONE.

2023-04-06 10:58 UTC, maugustosilva commented
/packit retest-failed

2023-04-06 12:12 UTC, maugustosilva commented
@Koncpa I am seeing some really weird errors here, such as `line 1379: keylime_sign_runtime_policy: command not found`. Before we debug further, please rebase and let's rerun the tests.

2023-04-14 09:05 UTC, Koncpa commented
/packit retest-failed

2023-04-19 01:27 UTC, merged