mba: Add a skip custom policies option when loading mba.
keylime/keylime pull request #1607
Opened 2024-08-07 13:30 UTC by marcostork

Allowing the skipping of custom policies, known only to the verifier, will enable the tenant to call MBA without consulting the verifier config file.

Resolves: #1541

2024-08-07 14:37 UTC, ansasaki requested changes
Could you please update the `load_imports()` documentation comments to reflect the changes?

And you need to add you sign-off to all commits to pass the DCO test

2024-08-09 09:30 UTC, ansasaki commented
The failint linting issues are unrelated with the changes.

@kkaarreell Would it be possible to confirm this makes the tenant to not load the `verifier.conf anymore`

2024-08-09 10:05 UTC, kkaarreell commented
> The failint linting issues are unrelated with the changes.
> 
> @kkaarreell Would it be possible to confirm this makes the tenant to not load the `verifier.conf ` anymore?

Hi, according to tenant logs it no longer reads verifier.conf, it still accesses ca.conf though.

2024-08-09 10:10 UTC, ansasaki commented
> > The failint linting issues are unrelated with the changes.
> > @kkaarreell Would it be possible to confirm this makes the tenant to not load the `verifier.conf ` anymore?
> 
> Hi, according to tenant logs it no longer reads verifier.conf, it still accesses ca.conf though.

This is expected, the `ca.conf` and `logging.conf` were never separated per component. Maybe this is an improvement we should aim to fix. In my opinion, it makes sense to be able to configure them separately per component.

2024-08-09 14:09 UTC, ansasaki approved these changes
I think with the proposed changes we make a compromise: the quote is still verified by the tenant, but will not support special modules to be used by the measured boot policy, only the default modules.

And this fixes the regression of the tenant requiring the `verifier.conf`.

@maugustosilva Would this be ok for you?

2024-08-09 16:21 UTC, maugustosilva commented
This is exactly what we wanted as the compromise (i.e., quote has to be checked, PCR#16 and all that), and if the `lint` issues are not related to this change LGTM.

2024-08-09 16:21 UTC, maugustosilva approved these changes

2024-08-12 18:40 UTC, maugustosilva commented
Ok, the `lint` errors are not related to this PR. I will merge and carve out some time to open a separated PR to deal with it.

2024-08-12 18:40 UTC, merged