Add missing license note
keylime/keylime pull request #1645
Opened 2024-09-19 08:18 UTC by sarroutbi

In order to homogeneize all files, it would be
recommended to add license header to all of them

2024-09-19 11:47 UTC, ansasaki submitted a review, later dismissed

2024-09-19 12:04 UTC, THS-on requested changes
I wouldn't reintroduce them. Rather remove the rest leftover ones. See discussion here, that we had a while back: https://github.com/keylime/keylime/issues/830

2024-09-24 08:29 UTC, ansasaki commented
> I wouldn't reintroduce them. Rather remove the rest leftover ones. See discussion here, that we had a while back: #830

I didn't have this context, thank you for pointing out to the discussion.

@sarroutbi Thank you for the contribution, but apparently the preference is to not add the license header, but rather drop it from the files that still have it. If you have free cycles and are willing to contribute in this front, maybe we could reverse the purpose of this PR. Otherwise I think we should close this. I'll drop my approval for now, I'll let you decide.

2024-09-24 12:41 UTC, sarroutbi commented
> > I wouldn't reintroduce them. Rather remove the rest leftover ones. See discussion here, that we had a while back: #830
> 
> I didn't have this context, thank you for pointing out to the discussion.
> 
> @sarroutbi Thank you for the contribution, but apparently the preference is to not add the license header, but rather drop it from the files that still have it. If you have free cycles and are willing to contribute in this front, maybe we could reverse the purpose of this PR. Otherwise I think we should close this. I'll drop my approval for now, I'll let you decide.

OK. It makes sense to close it. Sorry for the noise.

2024-09-24 12:41 UTC, closed without merging