Mysql compatibility
keylime/keylime pull request #369
Opened 2020-09-29 17:47 UTC by maugustosilva

This commit implements the minimal set of changes required to make sure Keylime can use a MySQL database. This involved mostly small fixes to Verifier and Registrar DB schema (mostly adding lengths for the "String" (mapped to "VarChar") columns). The only relevant exception is the changing of "ima_whitelist" column from "String" to "Text". Tested on both MySQL 5.7.31 and SQLite.

2020-09-30 16:47 UTC, mpeters requested changes

2020-09-30 17:10 UTC, lukehinds commented on keylime/registrar_common.py
> +                    try :
+1. I like that idea. I always get a little nervous about an `except` with `pass` in case we might get an error which we then `pass` on.

2020-09-30 21:13 UTC, maugustosilva commented on keylime/registrar_common.py
> +                    try :
Pushed the requested changes

2020-10-01 14:50 UTC, mpeters approved these changes
There were some failures in CI but I was able to verify that the tests pass locally on this branch for me and now CI has changed it's mind as well :)

So LGTM

2020-10-05 22:04 UTC, lukehinds commented
you should have merge rights @maugustosilva , if not let us know and we can ship this.

2020-10-07 13:53 UTC, maugustosilva commented
@lukehinds I don't have merge rights.

2020-10-07 13:59 UTC, mpeters commented
@maugustosilva if you rebase, I'll merge it for you.

2020-10-08 17:27 UTC, maugustosilva commented
I messed up during my rebase here. It was simply faster to create a new PR and apply it as a patch. Please look for #376 instead, exactly the same contents.

2020-10-08 17:27 UTC, closed without merging