Replace m2crypto with python-cryptography
keylime/keylime pull request #747
Opened 2021-09-02 14:32 UTC by sergio-correia

python-cryptography is already used in parts of the project, so it would
make sense to not use multiple libraries that can do the same thing.

It is also better maintained than M2Crypto and having one less dependency
is always a good thing.

Test coverage slightly improved as well.

2021-09-02 19:09 UTC, stefanberger requested changes

2021-09-02 19:09 UTC, stefanberger commented on keylime/ca_impl_cfssl.py
> +        privkey_path = os.path.abspath("%s/ca-key.pem" % secdir)
use `{secdir}` to be consistent?

2021-09-02 19:09 UTC, stefanberger commented on keylime/ca_impl_cfssl.py
> +        cacert_path = os.path.abspath("%s/cacert.crt" % secdir)
same here?

2021-09-03 10:58 UTC, sergio-correia commented on keylime/ca_impl_cfssl.py
> +        privkey_path = os.path.abspath("%s/ca-key.pem" % secdir)
Thanks, this was updated.

2021-09-03 18:46 UTC, stefanberger commented
> Test coverage slightly improved as well.

Would be good if we could show the test coverage via coveralls.io some day...

Otherwise the PR looks good to me.

2021-09-13 17:12 UTC, maugustosilva approved these changes

2021-09-13 19:11 UTC, merged