Fix LONGTEXT column type migration for MySQL
keylime/keylime pull request #866
Opened 2022-01-31 16:07 UTC by kkaarreell

Without this fix LONGTEXT column type is converted to TEXT type
which isn't big enough to store large data like allowlist.

Signed-off-by: Karel Srot <ksrot@redhat.com>

2022-01-31 16:09 UTC, THS-on approved these changes
LGTM

2022-01-31 17:36 UTC, mpeters requested changes
You can't update an existing migration with changes because it won't work on existing installs. You must create a new migration for that.

2022-01-31 17:40 UTC, THS-on commented
> You can't update an existing migration with changes because it won't work on existing installs. You must create a new migration for that.

I think it is fine because it is currently broken, so nobody could have a working install with that. We already did something similar here: https://github.com/keylime/keylime/pull/815

The test is failing because of an upstream issue: https://github.com/sqlalchemy/alembic/issues/982

2022-01-31 17:46 UTC, maugustosilva commented
I can confirm it is currently broken (for a MySQL test installation).

2022-01-31 17:49 UTC, mpeters commented
It's only broken if they try to use large allowlists. Maybe they were doing signatures before, or had small allowlists and large exclude lists (focusing only on the kernel or something else). Doing the fix like this instead of as a new migration will mean they will have to destroy their database, then upgrade and let keylime recreate the schema. I'm against any fix that requires something like this which can just be a new migration and upgrade like any other.

2022-01-31 18:54 UTC, THS-on commented
> It's only broken if they try to use large allowlists.

Oh, I thought it was fully broken for MySQL. If not then I agree that we need to add an migration on top of this fix to also change it current installations.

2022-01-31 18:59 UTC, kkaarreell commented
Would that be just another file with different name? Or is it more complicated?

2022-01-31 19:05 UTC, THS-on commented
> Would that be just another file with different name? Or is it more complicated?

You need to create a new migration file with alembic:
```
alembic -c keylime/migrations/alembic.ini revision -m "Added account table"
```

2022-01-31 19:21 UTC, mpeters commented
Alembic can be a tricky tool to use as it's not in the normal development flow. I don't mind taking a crack at it if you'd like @kkaarreell

2022-01-31 19:23 UTC, maugustosilva commented
@mpeters I have some free time now and can do that... whomever does it, please keep in mind that the `mb_refstate` column needs to be fixed too

2022-01-31 19:24 UTC, kkaarreell commented
> Alembic can be a tricky tool to use as it's not in the normal development flow. I don't mind taking a crack at it if you'd like @kkaarreell

Please do @mpeters or @maugustosilva . Thank you.

2022-01-31 19:24 UTC, mpeters commented
> @mpeters I have some free time now and can do that... whomever does it, please keep in mind that the `mb_refstate` column needs to be fixed too

@maugustosilva would you mind taking a crack it since you want this other change in there as well?

2022-01-31 19:28 UTC, maugustosilva commented
Certainly, on it

2022-01-31 19:42 UTC, kkaarreell commented
Should I close this PR?

2022-01-31 20:24 UTC, kkaarreell commented
I am sorry, I am already OOO, will check it tomorrow. Eventually, you can check it using tests from pgsql branch of keylime-tests. Either on Fedora system with tmt or by modifying the test to run additional SQL command and creating PR for keylime-tests repo.

2022-01-31 21:09 UTC, kkaarreell commented
> @kkaarreell while attempting to deploy with `MySQL`, I see the `allowlist` column is already of type `LONGTEXT`, but `mb_restate` is not. Are you seeing differently in `PostgreSQL`?

To clarify, the problem I was observing was with mariadb on F35. PostgreSQL didn't manifest that problem with insufficient field size for allow list.

2022-02-01 14:09 UTC, mpeters commented
New migration was added to fix this in https://github.com/keylime/keylime/pull/871

2022-02-01 14:09 UTC, closed without merging